#!/bin/bash

case "$1" in
    log)
        tail -n 60 -F /var/log/honeypottery/honeypottery.log
    ;;

    install)
        mkdir -p /var/log/honeypottery
        chmod -R 777 /var/log/honeypottery

        case "$OSTYPE" in
            linux*)
                sudo systemctl disable tomcat9
                cp target/*.war /var/lib/tomcat*/webapps/
                sudo systemctl enable tomcat9
                ;;
            darwin*)
                brew services stop tomcat
                sudo sh -c "echo 'UMASK=\"0022\"' > /usr/local/Cellar/tomcat/9.0.30/libexec/bin/setenv.sh"
                cp target/*.war /usr/local/Cellar/tomcat/*/libexec/webapps/
                brew services start tomcat 2> /dev/null
                ;;
        esac
        echo "servlet: war file installed."
    ;;

    uninstall)
        case "$OSTYPE" in
            linux*)
                rm /var/lib/tomcat*/webapps/*.war ;;
            darwin*)
                rm /usr/local/Cellar/tomcat/*/libexec/webapps/*.war ;;
        esac
        echo "servlet: war file removed."
    ;;

    *)
        echo "servlet: Unrecognized command - please use 'install', 'uninstall' or 'log'."
        exit 1
    ;;
esac
