#!/bin/bash

case "$1" in
    log)

        case "$OSTYPE" in
            linux*)
                tail -n 60 -F /etc/tomcat/apache-tomcat-9.0.41/logs/catalina.out ;;
            darwin*)
                tail -n 60 -F /usr/local/Cellar/tomcat/*/libexec/logs/catalina.*.log ;;
        esac
    ;;

    start)
        case "$OSTYPE" in
            linux*)
                rm -r /etc/tomcat/apache-tomcat-9.0.41/logs/catalina.*
                sudo /etc/tomcat/apache-tomcat-9.0.41/bin/startup.sh
                ;;
            darwin*)
                rm -r /usr/local/Cellar/tomcat/*/libexec/logs/catalina.*
                brew services start tomcat 
                ;;
        esac
    ;;

    stop)
        case "$OSTYPE" in
            linux*)
                sudo /etc/tomcat/apache-tomcat-9.0.41/bin/shutdown.sh ;;
            darwin*)
                brew services stop tomcat ;;
        esac
    ;;

    restart)
        case "$OSTYPE" in
            linux*)
                rm -r /etc/tomcat/apache-tomcat-9.0.41/logs/catalina.*
                sudo /etc/tomcat/apache-tomcat-9.0.41/bin/shutdown.sh
                sudo /etc/tomcat/apache-tomcat-9.0.41/bin/startup.sh
                ;;
            darwin*)
                rm -r /usr/local/Cellar/tomcat/*/libexec/logs/catalina.*
                brew services restart tomcat 
                ;;
        esac
    ;;

    *)
        echo "tomcat: Unrecognized command - please use 'start', 'stop', 'restart' or 'log'."
        exit 1
    ;;    
esac
